# Uncomment the next line to define a global platform for your project
platform :ios, '18.5'

target 'LiveEventsStreaming' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LiveEventsStreaming

  target 'LiveEventsStreamingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LiveEventsStreamingUITests' do
    # Pods for testing
  end

end
